### ISSUE TITLE
What does gold_file refer to

### ISSUE THREAD

**Issue by sijiawang1994** [xinyadu/eeqa#1]
Hi, 

In code/script_args_qa_thresh.sh and code/script_args_qa.sh, what does the argument gold_file refer to?

It is both used in line 548 and line 698 in code/run_args_qa_thresh.py, yet they are used for evaluating devel set and test set respectively. How is one gold file able to evaluate both sets?

Thank you!

**Comment by xinyadu** [comment]
Hi @sijiawang1994 , I assigned gold_file to dev when only --do_train (during training) is true, and gold_file to test when only --do_eval (during test) is true.

You can also add another argument for each of the gold_file.

-Xinya

**Comment by sijiawang1994** [comment]
Thank you for the clarification!
