### ISSUE TITLE
How to download SciERC and GENIA datasets ?

### ISSUE THREAD

**Issue by Toan-it-mta** [xinyadu/eeqa#15]
How to get SciERC and GENIA datasets ? In the eeqa/proc/DATA.md file, I see instructions to download 2 datasets. But I can't find ./scripts/data/get_scierc.sh and ./scripts/data/get_genia.sh files to download. Thanks

**Comment by kit57** [comment]
Hi, @Toan-it-mta 

I don't see those .sh files either. However, I found the datasets online. You can download them here [SciERC](http://nlp.cs.washington.edu/sciIE/) and here [Genia](http://www.geniaproject.org/genia-corpus/pos-annotation)
