### ISSUE TITLE
Why can't I reproduce the result in the paper?

### ISSUE THREAD

**Issue by ll0iecas** [xinyadu/eeqa#5]
@xinyadu 
Hello, I run the code as required，just get trigger_classification: P=73.333	R=68.238	F1=70.694 when choose the best trigger question strategy (while the corresponding result P=71.12 R=73.70 F1=72.39 in the paper). Are there any other recommendation or parameter option to improve?

**Comment by liutaonuist** [comment]
I meet the same question and I can not deal with it, could you give some advice on whether  there are  any other recommendation or parameter option to improve?
